- name: Setup wg0 configuration
  template:
    src: wg0.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: 0600
  notify: Restart wireguard

- name: Ensure kernel module is loaded
  modprobe: name=wireguard state=present

- name: Ensure wireguard is started at boot
  service: name=wg-quick@wg0 state=started enabled=yes

- name: Open VPN port for Wireguard
  ufw: rule=allow direction=in port={{ wg_port }} interface={{ wg_internal_iface }}

- name: Allow all traffic on Wireguard interface
  ufw: rule=allow direction=in interface=wg0
