- name: Ensure correct kernel headers are installed.
  shell: "apt-get -y install linux-headers-$(uname -r)"

- name: Install ppa apt repository
  apt_repository: repo=ppa:wireguard/wireguard

- name: Install wireguard-dkms
  apt: name=wireguard-dkms

- name: Install wireguard-tools
  apt: name=wireguard-tools
